const Allitems = [
  {
    donor: "donor's name",
    donorEmail: "a@a.com",
    name: "new product name",
    claimedBy:"someone",
    pickedUp: "",
    Description: "lorem stuff", 
    pictures: "none",
    estimatedValue: 100,
    itemCondition: "Poor",
    Location: "78216",
    dateCreated: "friday",
    category: "Electronics",
  },
  {
    donor: "donor's name",
    donorEmail: "a@a.com",
    name: "new product name",
    claimedBy:"someone",
    pickedUp: "someone",
    Description: "lorem stuff", 
    pictures: "none",
    estimatedValue: 100,
    itemCondition: "Poor",
    Location: "78216",
    dateCreated: "friday",
    category: "Electronics",
  },
  {
    donor: "donor's name",
    donorEmail: "a@a.com",
    name: "new product name",
    claimedBy:"someone",
    pickedUp: "",
    Description: "lorem stuff", 
    pictures: "none",
    estimatedValue: 100,
    itemCondition: "Poor",
    Location: "78216",
    dateCreated: "friday",
    category: "Electronics",
  },
  {
    donor: "donor's name",
    donorEmail: "a@a.com",
    name: "new product name",
    claimedBy:null,
    pickedUp: "",
    Description: "lorem stuff", 
    pictures: "none",
    estimatedValue: 100,
    itemCondition: "Poor",
    Location: "78216",
    dateCreated: "friday",
    category: "Electronics",
  },
  {
    donor: "donor's name",
    donorEmail: "a@a.com",
    name: "new product name",
    claimedBy:null,
    pickedUp: "",
    Description: "lorem stuff", 
    pictures: "none",
    estimatedValue: 100,
    itemCondition: "Poor",
    Location: "78216",
    dateCreated: "friday",
    category: "Electronics",
  },
  {
    donor: "donor's name",
    donorEmail: "a@a.com",
    name: "new product name",
    claimedBy:null,
    pickedUp: "none",
    Description: "lorem stuff", 
    pictures: "none",
    estimatedValue: 100,
    itemCondition: "Poor",
    Location: "78216",
    dateCreated: "friday",
    category: "Electronics",
  },
  {
    donor: "donor's name",
    donorEmail: "a@a.com",
    name: "new product name",
    claimedBy:null,
    pickedUp: "none",
    Description: "lorem stuff", 
    pictures: "none",
    estimatedValue: 100,
    itemCondition: "Poor",
    Location: "78216",
    dateCreated: "friday",
    category: "Electronics",
  }
];

module.exports = Allitems ;